/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.senai.sp.jandira.gui;

import br.senai.sp.jandira.dao.EspecialidadeDAO;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 22282179
 */
public class EspecialidadesPanel extends javax.swing.JPanel {

    /**
     * Creates new form EspecialidadesPanel
     */
    public EspecialidadesPanel() {
        initComponents();
        EspecialidadeDAO.criarListaDeEspecialidades();
        ajustarTabela();
        preencherTabela();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollListaEspecialidades = new javax.swing.JScrollPane();
        jTable1Listas = new javax.swing.JTable();
        buttonDeleteEspecialidade = new javax.swing.JButton();
        buttonEditarEspecialidade = new javax.swing.JButton();
        buttonAdicionarEspecialidade = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Especialidades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 255))); // NOI18N
        setPreferredSize(new java.awt.Dimension(880, 320));
        setLayout(null);

        jTable1Listas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollListaEspecialidades.setViewportView(jTable1Listas);

        add(scrollListaEspecialidades);
        scrollListaEspecialidades.setBounds(20, 40, 820, 200);

        buttonDeleteEspecialidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/delete32.png"))); // NOI18N
        buttonDeleteEspecialidade.setToolTipText("Delete");
        buttonDeleteEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteEspecialidadeActionPerformed(evt);
            }
        });
        add(buttonDeleteEspecialidade);
        buttonDeleteEspecialidade.setBounds(680, 260, 38, 40);

        buttonEditarEspecialidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/edit32.png"))); // NOI18N
        buttonEditarEspecialidade.setToolTipText("Editar");
        add(buttonEditarEspecialidade);
        buttonEditarEspecialidade.setBounds(740, 260, 38, 40);

        buttonAdicionarEspecialidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/plus32.png"))); // NOI18N
        buttonAdicionarEspecialidade.setToolTipText("Adicionar");
        buttonAdicionarEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarEspecialidadeActionPerformed(evt);
            }
        });
        add(buttonAdicionarEspecialidade);
        buttonAdicionarEspecialidade.setBounds(800, 260, 38, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDeleteEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteEspecialidadeActionPerformed
       //pegar a linha e a coluna que está selecionada  e excluir 
        int linha = jTable1Listas.getSelectedRow();
        if(linha != -1){
            excluirEspecialidade(linha);
        }else{ //se nada for selecionado aparece uma mensagem de atenção
            JOptionPane.showMessageDialog(this, "Por favor,selecione a especialidade que deseja excluir!"
                    ,"Atenção",
                    JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_buttonDeleteEspecialidadeActionPerformed
       private void excluirEspecialidade(int linha){
        String codigoStr = jTable1Listas.getValueAt(linha, 0).toString();
        Integer codigo = Integer.valueOf(codigoStr);
        
        
        int resposta = JOptionPane.showConfirmDialog(
                this, 
                "Você confirma a exclusão ?",
               JOptionPane.QUESTION_MESSAGE,
               JOptionPane.YES_NO_OPTION);
        int resposta = JOptionPane.showConfirmDialog(this, "Você confirma a exclusão?", "Atenção", 0)
        
        EspecialidadeDAO.excluir(codigo);
        
        preencherTabela();
         
}
    private void buttonAdicionarEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarEspecialidadeActionPerformed
        EspecialidadeJDialog especialidade = new EspecialidadeJDialog(null, true);//criando a tela modal de adicionar especialidades
        especialidade.setVisible(true); //fazendo a tela aparecer quando apertamos o botão adicionar de especialidades
        preencherTabela();
    }//GEN-LAST:event_buttonAdicionarEspecialidadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionarEspecialidade;
    private javax.swing.JButton buttonDeleteEspecialidade;
    private javax.swing.JButton buttonEditarEspecialidade;
    private javax.swing.JTable jTable1Listas;
    private javax.swing.JScrollPane scrollListaEspecialidades;
    // End of variables declaration//GEN-END:variables

    private void preencherTabela() {
        jTable1Listas.setModel(EspecialidadeDAO.getEspecialidadeModel());
        ajustarTabela();
     
  
    }
    private void ajustarTabela(){
        //Impedir o úsuario de movimentar as colunas
        jTable1Listas.getTableHeader().setReorderingAllowed(false);
        
        //bloquear a edição das células da tabela
        jTable1Listas.setDefaultEditor(Object.class, null);
        
        //Definir a largura das colunas
        jTable1Listas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable1Listas.getColumnModel().getColumn(0).setPreferredWidth(150);
        jTable1Listas.getColumnModel().getColumn(1).setPreferredWidth(170);
        jTable1Listas.getColumnModel().getColumn(2).setPreferredWidth(496);
        
    }
    

}
